list = ['wild strawberry', 'apple', 'pear', 'pineapple', 'strawberry']

print('Temporary sorted')
print(sorted(list))
print('Original')
print(list)
print('\n')
print('Temporary reversed sorted')
print(sorted(list, reverse=True))
print('Original')
print(list)
print('\n')
print('Reversed')
list.reverse()
print(list)
print('Original')
list.reverse()
print(list)
print('\n')
print('sorted')
list.sort()
print(list)
print('\n')
print('reverse sorted')
list.sort(reverse=True)
print(list)
print('\n')
print(list[1].title())
print(list[1].upper())
print(list[1].lower())

